config/routes.rb
TumblrToyProject::Application.routes.draw do
  resources :tumblrs

  resources :authorizations

  resources :users

 root :to => 'sessions#new'

  # resources :users, :only => [ :show, :edit, :update ]

  post '/oauth/request_token' => 'sessions#new'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
end

app/models/tumblr.rb
class Tumblr < ActiveRecord::Base
  attr_accessible :followers, :title, :total_notes, :total_posts, :url
end

app/controllers/tumblrs_controller.rb
class TumblrsController < ApplicationController
  # GET /tumblrs
  # GET /tumblrs.json
  def index
    @tumblrs = Tumblr.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tumblrs }
    end
  end

  # GET /tumblrs/1
  # GET /tumblrs/1.json
  def show
    @tumblr = Tumblr.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tumblr }
    end
  end

  # GET /tumblrs/new
  # GET /tumblrs/new.json
  def new
    @tumblr = Tumblr.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tumblr }
    end
  end

  # GET /tumblrs/1/edit
  def edit
    @tumblr = Tumblr.find(params[:id])
  end

  # POST /tumblrs
  # POST /tumblrs.json
  def create
    @tumblr = Tumblr.new(params[:tumblr])

    respond_to do |format|
      if @tumblr.save
        format.html { redirect_to @tumblr, notice: 'Tumblr was successfully created.' }
        format.json { render json: @tumblr, status: :created, location: @tumblr }
      else
        format.html { render action: "new" }
        format.json { render json: @tumblr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tumblrs/1
  # PUT /tumblrs/1.json
  def update
    @tumblr = Tumblr.find(params[:id])

    respond_to do |format|
      if @tumblr.update_attributes(params[:tumblr])
        format.html { redirect_to @tumblr, notice: 'Tumblr was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tumblr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tumblrs/1
  # DELETE /tumblrs/1.json
  def destroy
    @tumblr = Tumblr.find(params[:id])
    @tumblr.destroy

    respond_to do |format|
      format.html { redirect_to tumblrs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tumblrs_helper.rb
module TumblrsHelper
end

app/views/tumblrs/_form.html.erb
<%= form_for(@tumblr) do |f| %>
  <% if @tumblr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tumblr.errors.count, "error") %> prohibited this tumblr from being saved:</h2>

      <ul>
      <% @tumblr.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :followers %><br />
    <%= f.number_field :followers %>
  </div>
  <div class="field">
    <%= f.label :total_posts %><br />
    <%= f.number_field :total_posts %>
  </div>
  <div class="field">
    <%= f.label :total_notes %><br />
    <%= f.number_field :total_notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tumblrs/edit.html.erb
<h1>Editing tumblr</h1>

<%= render 'form' %>

<%= link_to 'Show', @tumblr %> |
<%= link_to 'Back', tumblrs_path %>

app/views/tumblrs/index.html.erb
<h1>Listing tumblrs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Followers</th>
    <th>Total posts</th>
    <th>Total notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tumblrs.each do |tumblr| %>
  <tr>
    <td><%= tumblr.title %></td>
    <td><%= tumblr.url %></td>
    <td><%= tumblr.followers %></td>
    <td><%= tumblr.total_posts %></td>
    <td><%= tumblr.total_notes %></td>
    <td><%= link_to 'Show', tumblr %></td>
    <td><%= link_to 'Edit', edit_tumblr_path(tumblr) %></td>
    <td><%= link_to 'Destroy', tumblr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tumblr', new_tumblr_path %>

app/views/tumblrs/new.html.erb
<h1>New tumblr</h1>

<%= render 'form' %>

<%= link_to 'Back', tumblrs_path %>

app/views/tumblrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @tumblr.title %>
</p>

<p>
  <b>Url:</b>
  <%= @tumblr.url %>
</p>

<p>
  <b>Followers:</b>
  <%= @tumblr.followers %>
</p>

<p>
  <b>Total posts:</b>
  <%= @tumblr.total_posts %>
</p>

<p>
  <b>Total notes:</b>
  <%= @tumblr.total_notes %>
</p>


<%= link_to 'Edit', edit_tumblr_path(@tumblr) %> |
<%= link_to 'Back', tumblrs_path %>