config/routes.rb
TumblrToyProject::Application.routes.draw do
  resources :tumblrs

  resources :authorizations

  resources :users

 root :to => 'sessions#new'

  # resources :users, :only => [ :show, :edit, :update ]

  post '/oauth/request_token' => 'sessions#new'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :secret, :token, :uid
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  # GET /authorizations
  # GET /authorizations.json
  def index
    @authorizations = Authorization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authorizations }
    end
  end

  # GET /authorizations/1
  # GET /authorizations/1.json
  def show
    @authorization = Authorization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authorization }
    end
  end

  # GET /authorizations/new
  # GET /authorizations/new.json
  def new
    @authorization = Authorization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authorization }
    end
  end

  # GET /authorizations/1/edit
  def edit
    @authorization = Authorization.find(params[:id])
  end

  # POST /authorizations
  # POST /authorizations.json
  def create
    @authorization = Authorization.new(params[:authorization])

    respond_to do |format|
      if @authorization.save
        format.html { redirect_to @authorization, notice: 'Authorization was successfully created.' }
        format.json { render json: @authorization, status: :created, location: @authorization }
      else
        format.html { render action: "new" }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorizations/1
  # PUT /authorizations/1.json
  def update
    @authorization = Authorization.find(params[:id])

    respond_to do |format|
      if @authorization.update_attributes(params[:authorization])
        format.html { redirect_to @authorization, notice: 'Authorization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1
  # DELETE /authorizations/1.json
  def destroy
    @authorization = Authorization.find(params[:id])
    @authorization.destroy

    respond_to do |format|
      format.html { redirect_to authorizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_form.html.erb
<%= form_for(@authorization) do |f| %>
  <% if @authorization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorization.errors.count, "error") %> prohibited this authorization from being saved:</h2>

      <ul>
      <% @authorization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :secret %><br />
    <%= f.text_field :secret %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorizations/edit.html.erb
<h1>Editing authorization</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorization %> |
<%= link_to 'Back', authorizations_path %>

app/views/authorizations/index.html.erb
<h1>Listing authorizations</h1>

<table>
  <tr>
    <th>Token</th>
    <th>Secret</th>
    <th>Provider</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorizations.each do |authorization| %>
  <tr>
    <td><%= authorization.token %></td>
    <td><%= authorization.secret %></td>
    <td><%= authorization.provider %></td>
    <td><%= authorization.uid %></td>
    <td><%= link_to 'Show', authorization %></td>
    <td><%= link_to 'Edit', edit_authorization_path(authorization) %></td>
    <td><%= link_to 'Destroy', authorization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorization', new_authorization_path %>

app/views/authorizations/new.html.erb
<h1>New authorization</h1>

<%= render 'form' %>

<%= link_to 'Back', authorizations_path %>

app/views/authorizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Token:</b>
  <%= @authorization.token %>
</p>

<p>
  <b>Secret:</b>
  <%= @authorization.secret %>
</p>

<p>
  <b>Provider:</b>
  <%= @authorization.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authorization.uid %>
</p>


<%= link_to 'Edit', edit_authorization_path(@authorization) %> |
<%= link_to 'Back', authorizations_path %>